### ISSUE TITLE
Exception after adding the plugin and setting up my yamaha reciever

### ISSUE THREAD

**Issue by zvaehn** [NorthernMan54/homebridge-yamaha-home#1]
```
Unhandled rejection ReferenceError: sysIds is not defined
    at /usr/local/lib/node_modules/homebridge-yamaha-home/index.js:169:13
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
```

**Comment by NorthernMan54** [comment]
Can you re-install and try again.

PS I'm still finalizing the setup of this, and have not completed the optimization for Alexa and homebridge-alexa

**Comment by jczwo** [comment]
I got this error too. Re-install doesn't help. Before the "sysIds is not defined" error I also got:

Unhandled rejection TypeError: Cannot read property 'YAMAHA_AV' of null
    at YamahaAVRPlatform.<anonymous> (/usr/lib/node_modules/homebridge-yamaha-home/index.js:164:21)
    at tryCatcher (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/timers.js:26:46)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)

**Comment by NorthernMan54** [comment]
Okay, I just made some changes that should resolve this, please try again

@jczwo @zvaehn

**Comment by jczwo** [comment]
SysIds error is gone. Next one appears:

Unhandled rejection TypeError: Cannot read property 'YAMAHA_AV' of null
    at YamahaAVRPlatform.<anonymous> (/usr/lib/node_modules/homebridge-yamaha-home/index.js:164:21)
    at tryCatcher (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/timers.js:26:46)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)


Unhandled rejection TypeError: this.log is not a function
    at /usr/lib/node_modules/homebridge-yamaha-home/index.js:172:14
    at tryCatcher (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:638:18)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/timers.js:26:46)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)


[2018-4-14 18:09:19] [yamaha-home] WARN: Got multiple systems with ID 00FB6053! Omitting duplicate!
[2018-4-14 18:09:32] [yamaha-home] Waited 10 seconds, stopping discovery.
[2018-4-14 18:09:32] [yamaha-home] Discovery finished, found 0 Yamaha AVR devices.

**Comment by NorthernMan54** [comment]
@jczwo I added more debugging, please update to the latest and try again

Also, what model of receiver do you have?  I'm wondering if its supported.

**Comment by jczwo** [comment]
I have an Yamaha HTR-4065 which is technically an RX-v473. Your plugin works fine since you switched repositiory. I tried commit [57c2fd1fb5bc8b2f0b36b5be2360659069d34029](https://github.com/NorthernMan54/homebridge-yamaha-home/tree/57c2fd1fb5bc8b2f0b36b5be2360659069d34029) again and it works fine.

On current release v0.0.9 the "Cannot read property 'YAMAHA_AV' of null" error is gone. But the "this.log is not a function" is still there. Homebridge is not starting. Here is the log:

[2018-4-15 10:18:29] [yamaha-home] Initializing yamaha-home platform...
[2018-4-15 10:18:29] [yamaha-home] Getting Yamaha AVR devices.
/usr/lib/node_modules/homebridge-yamaha-home/index.js:148
  this.log("Possible Yamaha device discovered", service.name, service.addresses);
       ^

TypeError: this.log is not a function
    at setupFromService (/usr/lib/node_modules/homebridge-yamaha-home/index.js:148:8)
    at YamahaAVRPlatform.accessories (/usr/lib/node_modules/homebridge-yamaha-home/index.js:117:7)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

**Comment by NorthernMan54** [comment]
I was scratching my head immensely with this as I was not seeing the same error, but then I realized you where using manual_addresses and it all made sense then.  I changed my setup to use manual addresses and was able to recreate your issue and have fingers crossed resolved it.

**Comment by jczwo** [comment]
Got some time today. Works like a charm. Great. Thank you!

**Comment by zvaehn** [comment]
Also works for me now 👍

**Comment by zvaehn** [comment]
When is the volume change triggered? It seems that my Yamaha recieves 3-4 volume changes when i slide the volume-slider on iOS from lets say 20-60%.

**Comment by posh1982** [comment]
hello!
I have an R-N301 and I install the plugin but i have this error:
Unhandled rejection TypeError: Cannot read property 'YAMAHA_AV' of null
at YamahaAVRPlatform. (/usr/lib/node_modules/homebridge-yamaha-home/index.js:164:21)
can you help me please?
thank you

**Comment by NorthernMan54** [comment]
@posh1982 Please open a new issue for this, and include more of the log from before the error.
