### ISSUE TITLE
Multiple AVR Receivers causing panic (Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d516d6c8-0a37-444e-8f47-d2f11a45ce8f)

### ISSUE THREAD

**Issue by jonathancatt** [NorthernMan54/homebridge-yamaha-home#10]
Just setting up this plug in our our network with multiple AVR and MusicCast speakers. It seems the fact that each receiver has a "MAIN" zone is causing the plugin to crash homebridge on initialization.

Here is the last output from the homebridge debug log:

> [2018-6-18 19:42:56] [yamaha-home] Waited 10 seconds, stopping discovery.
[2018-6-18 19:42:56] [yamaha-home] Discovery finished, found 9 Yamaha AVR devices.
[2018-6-18 19:42:56] [yamaha-home] Initializing platform accessory 'Workshop'...
[2018-6-18 19:42:56] [yamaha-home] Initializing platform accessory 'Living Room'...
[2018-6-18 19:42:56] [yamaha-home] Initializing platform accessory 'Home Theater'...
[2018-6-18 19:42:56] [yamaha-home] Initializing platform accessory 'Main'...
[2018-6-18 19:42:56] [yamaha-home] Initializing platform accessory 'Main'...

>/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
            ^
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d516d6c8-0a37-444e-8f47-d2f11a45ce8f
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:397:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at Timeout.timeoutFunction [as _onTimeout] (/usr/lib/node_modules/homebridge-yamaha-home/index.js:147:7)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by NorthernMan54** [comment]
One of the features of this plugin, is that each Zone is setup as an independent Accessory and each Accessory requires a unique name.  For the plugin to work correctly, you will need to name each zone uniquely.

**Comment by jonathancatt** [comment]
Is this done on the AVR or on the config.json? My apologies for the lack of knowledge, I only just picked up Homebridge recently and there is a fair amount of history to go back through...

Thanks!

**Comment by NorthernMan54** [comment]
This is done in the menu’s of the AVR itself.

**Comment by NorthernMan54** [comment]
For myself, I just put the unused switch etc in an room by themselves and turn off favourites and status updates so they are basically unseen
