### ISSUE TITLE
Error: The requested platform 'yamaha-home' was not registered by any plugin.

### ISSUE THREAD

**Issue by pbassham** [NorthernMan54/homebridge-yamaha-home#13]
Not sure why I am getting this. I installed through homebridge-config-ui-x v3.8.9 and is in the same folder with all the other plugins. 

```
[8/10/2018,` 10:01:35 AM] [People] WebHook: Started server on port '51828'.

/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
            ^
Error: The requested platform 'yamaha-home' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

Here is my config:
```
        {
            "platform": "yamaha-home",
            "play_volume": -40,
            "setMainInputTo": "HDMI1",
            "show_input_name": "yes",
            "party_switch": "no",
            "inputs_as_accessories": {
                "Yamaha RX-A860": {
                    "1": {
                        "name": "AppleTV",
                        "setInputTo": "HDMI1",
                        "set_default_volume": -49
                    },
                    "2": {
                        "name": "Chromecast",
                        "setInputTo": "HDMI2"
                    },
                    "3": {
                        "name": "Mac Mini",
                        "set_scene": "3",
                        "setInputTo": "HDMI3"
                    }
                }
            }
        }
```

**Comment by NorthernMan54** [comment]
@ozno. Any ideas as to what the problem is?

**Comment by NorthernMan54** [comment]
@pbassham please try again using the version 0.0.26

**Comment by pbassham** [comment]
Thanks. That seems to have fixed that.
