### ISSUE TITLE
scene selection impossible

### ISSUE THREAD

**Issue by arkhazim** [NorthernMan54/homebridge-yamaha-home#49]
hi ! i have an issue when setting up scene selection only with this plugin, my hole homebridega doesn't work anymore, here is my config and error message, can someone help me ?

[Focal] Waited 10 seconds, stopping discovery.
[5/25/2021, 00:46:21] [Focal] Discovery finished, found 8 Yamaha AVR devices.
[5/25/2021, 00:46:21] Initializing platform accessory 'PC1 / AI'...
[5/25/2021, 00:46:21] Initializing platform accessory 'PC2 / Auto'...
[5/25/2021, 00:46:21] Initializing platform accessory 'Music pure'...
[5/25/2021, 00:46:21] Initializing platform accessory 'Music nopure'...
[5/25/2021, 00:46:21] Initializing platform accessory 'Music 7ch'...
[5/25/2021, 00:46:21] Initializing platform accessory 'Music pure'...
[5/25/2021, 00:46:21] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7c8306a9-3ee2-46f2-b830-dd3b1e299df4
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:547:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:534:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at Timeout.timeoutFunction [as _onTimeout] (/usr/local/lib/node_modules/homebridge-yamaha-home/index.js:144:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[5/25/2021, 00:46:21] Got SIGTERM, shutting down Homebridge...

            "platform": "yamaha-home",
            "name": "Focal",
            "play_volume": -39,
            "show_input_name": "yes",
            "party_switch": "yes",
            "zone_controllers_only_for": "Main",
            "inputs_as_accessories": {
                "Yamaha": {
                    "1": {
                        "name": "PC1 / AI",
                        "set_scene": "1"
                    },
                    "2": {
                        "name": "PC2 / Auto",
                        "set_scene": "2"
                    },
                    "3": {
                        "name": "Music pure",
                        "set_scene": "5"
                    },
                    "4": {
                        "name": "Music nopure",
                        "set_scene": "6"
                    },
                    "5": {
                        "name": "Music 7ch",
                        "set_scene": "7"
                    },
                    "6": {
                        "name": "Music pure",
                        "set_scene": "8"
                    }
                }
            },
            "manual_addresses": {
                "Yamaha": "xxx.xxx.x.xx"
            }
        },
        {
            "ip": "192.168.1.39",
            "name": "Focal",
            "platform": "yamaha-avr"

**Comment by arkhazim** [comment]
error from me sorry resolved ! (same 2 names of accessory
