### ISSUE TITLE
Rx-as710d & wax-50

### ISSUE THREAD

**Issue by CoStiC** [NorthernMan54/homebridge-yamaha-home#51]
Hi, I've got two Ampli but can't start homebridge
I ve got 2 receivers, and it seems that party zone cause crashes
What should I do? Thank you for reply

[3/12/2022, 2:30:31 PM] Initializing platform accessory 'bluray'...
[3/12/2022, 2:30:31 PM] Initializing platform accessory 'Apple TV'...
[3/12/2022, 2:30:31 PM] Initializing platform accessory 'Party Mode'...
[3/12/2022, 2:30:31 PM] Initializing platform accessory 'Party Mode'...

[3/12/2022, 2:30:31 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 53f477e0-b32a-433c-9ae6-3b236476fc9f
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:594:15)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:552:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:539:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at Timeout.timeoutFunction [as _onTimeout] (/usr/local/lib/node_modules/homebridge-yamaha-home/index.js:144:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by NorthernMan54** [comment]
Do both your receivers have the same 'name' ?  I don't recall where the zone name is, but are they the same ?

**Comment by CoStiC** [comment]
> Do both your receivers have the same 'name' ?  I don't recall where the zone name is, but are they the same ?

Hey there! 

Thank you for replying. I ll post a bit more informations about my config for I'm pretty sure that it'll be easier :)

I've seen some other posts about "same" problem (https://github.com/NorthernMan54/homebridge-yamaha-home/issues/34#issue-615875078) and (https://github.com/NorthernMan54/homebridge-yamaha-home/issues/10#issue-333410675),
And I think i forget smthg. 

So here it is :

RX-AS710D
- Network name : "Ampli Salon"
- Main Zone : "Salon"
- Zone 2 : "Chambre"
- Inputs : 
"1": {
						"name":"bluray",
						"setInputTo": "HDMI1",
						"set_default_volume": -49
					},
					"2": {
						"name":"Salon Apple TV",
						"setInputTo": "HDMI2"
					}
// are the others inputs ignored if not mentioned?

WXA-50
- Network name : "Ampli Chambre"
- Main Zone : "Chambre"
- input :

"1": {
						"name":"Chambre Apple TV",
						"setInputTo": "AirPlay"
					}

I'm not sure how to configure config.json. Should I add them two into the "inputs_as_accessories" object as "Ampli Salon":{...} and "Ampli Chambre":{...}?

**Comment by NorthernMan54** [comment]
If you post your config with \`\`\` before and after it won't reformat it.  I can't determine what your asking above
